spring:
  config:
    import: optional:file:./secret.yml

portone:
  api:
    base-url: https://api.portone.io
    secret: ${PORTONE_API_SECRET:}
  webhook:
    secret: demo-webhook-secret-key
    secret-format: raw

logging:
  level:
    org.springframework.security: TRACE
    org.springframework.security.web.FilterChainProxy: TRACE
    org.springframework.web.filter: DEBUG