spring:
  config:
    import: optional:file:./secret.yml

portone:
  api:
    base-url: https://api.portone.io
    secret: ${PORTONE_API_SECRET:}
  webhook:
    secret: whsec_Rox/VRThQsgN0nop7RxWMydDaH0k4tHMqCdNgSm7LdU=
    secret-format: raw
